[tool.poetry]
name = "picobot"
version = "0.1.0"
description = ""
authors = ["Arthur Mesquita Pickcius <arthur.pickcius@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
python-telegram-bot = "^11.1"
dataset = "^1.1"
pillow = "^9.0"
python-slugify = "^4.0"
emoji = "^0.6.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
flake8 = "^3.7"
isort = "^4.3"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.black]
skip_string_normalization = true
line_length = 100

[tool.isort]
profile = "hug"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
